'use strict';
const $=id=>document.getElementById(id), world=$('world'), viewport=$('viewport');
const KEY='generic-exhibition-v1', categories=['Ulaşım türü 1','Ulaşım türü 2','Ulaşım türü 3','Ulaşım projesi'];
let projects=Array.from({length:10},(_,i)=>({title:`Proje ${String(i+1).padStart(2,'0')}`,category:categories[i%3],images:[]}));
let selected=-1, editing=0, imageIndex=0, camera={x:0,y:-30,z:1800,yaw:0,pitch:0}, target={...camera}, dirty=false, saveTimer, noticeTimer;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function notice(message){$('notice').textContent=message;$('notice').hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('notice').hidden=true,6000)}
function validate(data){if(!data||data.version!==1||!Array.isArray(data.projects)||data.projects.length!==10)throw Error('Dosya, 10 projeli sergi biçiminde olmalı.');return data.projects.map((p)=>{if(!p||typeof p.title!=='string'||!categories.includes(p.category)||!Array.isArray(p.images)||p.images.length>30)throw Error('Proje içeriği geçersiz.');return{title:p.title.slice(0,100),category:p.category,images:p.images.map(src=>{if(typeof src!=='string'||!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(src))throw Error('Desteklenmeyen görsel verisi.');return src})}})}
try{const stored=localStorage.getItem(KEY);if(stored)projects=validate(JSON.parse(stored))}catch(e){notice('Yerel kayıt okunamadı. Kaydettiğiniz JSON dosyasını açabilirsiniz.')}
function save(){clearTimeout(saveTimer);dirty=true;$('saveState').textContent='Değişiklikler kaydediliyor…';saveTimer=setTimeout(()=>{try{localStorage.setItem(KEY,JSON.stringify({version:1,projects}));$('saveState').textContent='Bu tarayıcıya kaydedildi. Taşımak için Projeyi kaydet kullanın.';dirty=false}catch(e){$('saveState').textContent='Tarayıcı depolama alanı dolu veya kullanılamıyor. Kaybı önlemek için Projeyi kaydet ile JSON indirin.';notice('Yerel kayıt yapılamadı. Projeyi kaydet ile dışa aktarın.')}},350)}
function element(tag,cls,text){const el=document.createElement(tag);if(cls)el.className=cls;if(text!==undefined)el.textContent=text;return el}
function surface(cls,w,h,x,y,z,rotation=''){const e=element('div','surface '+cls);e.style.cssText=`width:${w}px;height:${h}px;transform:translate3d(${x-w/2}px,${y-h/2}px,${z}px) ${rotation}`;world.append(e);return e}
surface('floor',2200,8000,0,360,-2600,'rotateX(90deg)');surface('ceiling',2200,8000,0,-620,-2600,'rotateX(90deg)');surface('wall',8000,980,-1100,-130,-2600,'rotateY(90deg)');surface('wall',8000,980,1100,-130,-2600,'rotateY(90deg)');surface('endWall',2200,980,0,-130,-6600);
for(let i=0;i<8;i++){const e=surface('light',1400,8,0,-605,800-i*900);e.style.background='#fffef1'}
for(let j=0;j<3;j++){let e=surface('floorLine',8,7600,-45+j*45,358,-2600,'rotateX(90deg)');e.style.background=['#388eac','#c4a55b','#528b6c'][j]}
const sign=element('div','hallSign');sign.style.transform='translate3d(-450px,-370px,-5500px)';sign.append(element('b','', 'PROJE ADI'),element('span','','ALT BAŞLIK'));world.append(sign);
const panels=[];
function position(i){return{x:i%2?510:-510,y:-40,z:-Math.floor(i/2)*1100}}
function renderPanel(i){let panel=panels[i];if(!panel){panel=element('button','artPanel');const p=position(i);panel.style.transform=`translate3d(${p.x-285}px,${p.y-177.5}px,${p.z}px)`;panel.addEventListener('click',()=>{if(dragMoved)return;if(selected===i)openViewer();else go(i)});world.append(panel);panels[i]=panel}panel.replaceChildren();panel.setAttribute('aria-label',`${projects[i].title}, yaklaş ve görseli aç`);if(projects[i].images.length){let img=element('img');img.src=projects[i].images[0];img.alt=projects[i].title;img.draggable=false;panel.append(img)}else{const p=element('div','placeholder'),img=element('img');img.src='assets/placeholder.svg';img.alt='Boş görsel alanı';img.draggable=false;p.append(img,element('span','','GÖRSELİNİZİ EKLEYİN'),element('b','',String(i+1).padStart(2,'0')));panel.append(p)}const plaque=element('div','plaque');plaque.append(element('strong','',`${String(i+1).padStart(2,'0')} / ${projects[i].title}`),element('small','',projects[i].category));panel.append(plaque)}
function render(){for(let i=0;i<10;i++)renderPanel(i);$('projectSelect').replaceChildren();projects.forEach((p,i)=>{let o=element('option','',`${i+1}. ${p.title}`);o.value=i;$('projectSelect').append(o)});$('projectSelect').value=editing;updateCaption()}
projects.forEach((p,i)=>{const b=element('button','',String(i+1).padStart(2,'0'));b.title=p.title;b.addEventListener('click',()=>go(i));$('stops').append(b)});
function updateCaption(){$('welcome').hidden=selected>=0;$('caption').hidden=selected<0;if(selected>=0){$('projectTitle').textContent=projects[selected].title;$('projectCategory').textContent=projects[selected].category;$('viewImage').textContent=projects[selected].images.length?'Görseli tam ekranda incele ↗':'Bu projeye görsel ekle ＋'}[...$('stops').children].forEach((b,i)=>{b.classList.toggle('active',i===selected);b.setAttribute('aria-current',i===selected?'step':'false');b.title=projects[i].title});$('prev').disabled=selected<0;$('next').disabled=selected===9}
function go(i){selected=Math.max(-1,Math.min(9,i));if(selected<0)target={x:0,y:-30,z:1800,yaw:0,pitch:0};else{const p=position(selected);const distance=1000*Math.max(570/(innerWidth*.67),355/(innerHeight*.57));target={x:p.x,y:p.y,z:p.z+distance,yaw:0,pitch:0}}updateCaption()}
function draw(){const ease=reduced?1:.085;for(const k of Object.keys(camera))camera[k]+=(target[k]-camera[k])*ease;world.style.transform=`translateZ(1000px) rotateX(${camera.pitch}deg) rotateY(${camera.yaw}deg) translate3d(${-camera.x}px,${-camera.y}px,${-camera.z}px)`;requestAnimationFrame(draw)}
let drag=null,dragMoved=false;viewport.addEventListener('pointerdown',e=>{if(e.button!==0)return;drag={x:e.clientX,y:e.clientY,yaw:target.yaw,pitch:target.pitch};dragMoved=false});viewport.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>6){dragMoved=true;target.yaw=drag.yaw+dx*.10;target.pitch=Math.max(-35,Math.min(35,drag.pitch-dy*.08))}});window.addEventListener('pointerup',()=>{drag=null;setTimeout(()=>dragMoved=false,50)});window.addEventListener('pointercancel',()=>drag=null);
viewport.addEventListener('wheel',e=>{e.preventDefault();target.z=Math.max(-5700,Math.min(2400,target.z+e.deltaY*.65))},{passive:false});
$('home').onclick=()=>go(-1);$('start').onclick=()=>go(0);$('next').onclick=()=>go(selected+1);$('prev').onclick=()=>go(selected-1);
function editor(open){$('editor').hidden=!open;if(open){editing=Math.max(selected,0);loadEditor()}}
$('editToggle').onclick=()=>editor($('editor').hidden);$('closeEditor').onclick=()=>editor(false);
function loadEditor(){$('projectSelect').value=editing;$('titleInput').value=projects[editing].title;$('categoryInput').value=projects[editing].category;$('imageList').replaceChildren();projects[editing].images.forEach((src,j)=>{const t=element('div','thumb'),im=element('img'),b=element('button','','×');im.src=src;im.alt=`Görsel ${j+1}`;b.setAttribute('aria-label',`Görsel ${j+1} sil`);b.onclick=()=>{projects[editing].images.splice(j,1);loadEditor();renderPanel(editing);updateCaption();save()};t.append(im,b,element('small','',`${j+1}. görsel`));$('imageList').append(t)})}
$('projectSelect').onchange=e=>{editing=Number(e.target.value);loadEditor();go(editing)};
$('titleInput').oninput=e=>{projects[editing].title=e.target.value;renderPanel(editing);updateCaption();$('projectSelect').options[editing].textContent=`${editing+1}. ${e.target.value}`;save()};
$('categoryInput').onchange=e=>{projects[editing].category=e.target.value;renderPanel(editing);updateCaption();save()};
function readImage(file){return new Promise((resolve,reject)=>{if(!['image/png','image/jpeg','image/webp'].includes(file.type))return reject(Error('Yalnızca PNG, JPG ve WebP eklenebilir.'));if(file.size>20*1024*1024)return reject(Error('Her görsel en fazla 20 MB olabilir.'));const r=new FileReader();r.onerror=()=>reject(Error('Görsel okunamadı.'));r.onload=()=>{const img=new Image();img.onload=()=>resolve(r.result);img.onerror=()=>reject(Error('Görsel dosyası çözümlenemedi.'));img.src=r.result};r.readAsDataURL(file)})}
$('imagesInput').onchange=async e=>{const index=editing,files=[...e.target.files];e.target.value='';if(projects[index].images.length+files.length>30)return notice('Bir projede en fazla 30 görsel olabilir.');try{const images=await Promise.all(files.map(readImage));projects[index].images.push(...images);renderPanel(index);if(editing===index)loadEditor();updateCaption();save();notice(`${images.length} görsel eklendi.`)}catch(err){notice(err.message)}};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify({version:1,projects})],{type:'application/json'}),url=URL.createObjectURL(blob),a=element('a');a.href=url;a.download='proje-sergisi.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);dirty=false;notice('Proje JSON olarak indirildi; görseller dosyanın içinde.')};
$('import').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{const loaded=validate(JSON.parse(await file.text()));projects=loaded;render();loadEditor();save();notice('Proje açıldı.')}catch(err){notice('Proje açılamadı: '+err.message)}};
function openViewer(){if(selected<0)return;if(!projects[selected].images.length){editor(true);return}imageIndex=0;showImage();$('viewer').showModal()}
function showImage(){const p=projects[selected];$('fullImage').src=p.images[imageIndex];$('fullImage').alt=p.title;$('viewerTitle').textContent=p.title;$('imageCount').textContent=`${imageIndex+1} / ${p.images.length}`;$('imagePrev').disabled=imageIndex===0;$('imageNext').disabled=imageIndex===p.images.length-1}
$('viewImage').onclick=openViewer;$('closeViewer').onclick=()=>$('viewer').close();$('imagePrev').onclick=()=>{if(imageIndex>0){imageIndex--;showImage()}};$('imageNext').onclick=()=>{if(imageIndex<projects[selected].images.length-1){imageIndex++;showImage()}};
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch(e){notice('Bu tarayıcı tam ekranı desteklemiyor. F11 ile açabilirsiniz.')}}
$('fullscreen').onclick=fullscreen;$('present').onclick=()=>{editor(false);document.body.classList.add('presenting');$('exitPresent').hidden=false;fullscreen()};$('exitPresent').onclick=()=>{document.body.classList.remove('presenting');$('exitPresent').hidden=true;if(document.fullscreenElement)document.exitFullscreen().catch(()=>{})};
window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName))return;if($('viewer').open){if(e.key==='ArrowLeft')$('imagePrev').click();if(e.key==='ArrowRight')$('imageNext').click();return}if(e.key==='ArrowRight'){e.preventDefault();go(selected+1)}if(e.key==='ArrowLeft'){e.preventDefault();go(selected-1)}if(e.key==='Home'){e.preventDefault();go(-1)}const key=e.key.toLowerCase(),angle=target.yaw*Math.PI/180,step=90;if(key==='w'||key==='s'){const d=key==='w'?-step:step;target.z=Math.max(-5700,Math.min(2400,target.z+d*Math.cos(angle)));target.x=Math.max(-850,Math.min(850,target.x-d*Math.sin(angle)))}if(key==='a'||key==='d'){const d=key==='a'?-step:step;target.x=Math.max(-850,Math.min(850,target.x+d*Math.cos(angle)));target.z=Math.max(-5700,Math.min(2400,target.z+d*Math.sin(angle)))}if(e.key==='Escape'){document.body.classList.remove('presenting');$('exitPresent').hidden=true;editor(false)}});
window.addEventListener('resize',()=>go(selected));window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});render();draw();
